import time 

while(True):
    print("WOW!!")
    time.sleep(1)

    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    print("WOW!!")
    time.sleep(0.3)
    break